
baseurl: "https://uncv2022.github.io"
color-scheme: "#1a2090" #the scheme can be any HEX code like "#334279"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

title: "Workshop on Uncertainty Quantification for Computer Vision"
subtitle: "[ECCV 2022 Workshop](https://eccv2022.ecva.net/)"

shorttitle: "UNCV Workshop @ ECCV 2022"
information: "ECCV 2022 Workshop on Uncertainty Quantification for Computer Vision." 

organizers: "UNCV Organizers"

deadlines:
  - item: Submission deadline
    date: July 10th, 2022
  
  - item: Notification of acceptance
    date: August 10th, 2022 

  - item: Camera-ready deadline
    date: August 22, 2022

